#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, displays
#Best School and then Hi on a new line
three=1
while [ $three -le 10 ]
do
	echo "Best School"
	if [ $three -eq 9 ]; then
		echo "Hi"
	fi
	three=$((three+1))
done
